kind: ManagedSet
apiVersion: kapitan.razee.io/v1alpha1
metadata:
  name: razee-demo-managed-set
  namespace: default
spec:
  resources:
    - apiVersion: "kapitan.razee.io/v1alpha1"
      kind: RemoteResource
      metadata:
        name: razee-demo-versions-remote
        namespace: default
      spec:
        requests:
          - options:
              url: https://raw.githubusercontent.com/mckaymic/RazeeDemo-CD/master/razee-demo-versions.yaml
    - apiVersion: "kapitan.razee.io/v1alpha1"
      kind: MustacheTemplate
      metadata:
        name: base-bom-template
        namespace: default
      spec:
        env:
        - name: type
          valueFrom:
            configMapKeyRef:
              name: clusterinfo
              key: type
        templates:
        - apiVersion: "kapitan.razee.io/v1alpha1"
          kind: RemoteResource
          metadata:
            name: base-remote-bom
            namespace: default
          spec:
            requests:
            - options:
                url: https://raw.githubusercontent.com/mckaymic/RazeeDemo-CD/master/{{type}}-bom.yaml